branches:
- name: master

plugins:
- '@semantic-release/commit-analyzer'
- '@semantic-release/release-notes-generator'
- '@semantic-release/changelog'
- '@semantic-release/npm'
- - '@semantic-release/exec'
  - prepareCmd: grunt release
- - '@semantic-release/git'
  - assets:
    - CHANGELOG.md
    - package.json
    - bin/*
    - dist/*.js
    - lib/*.js
- '@semantic-release/github'
