language: node_js
os: linux
dist: xenial
node_js: 14

install:
- npm install

script:
- npm run test

deploy:
  on:
    branch: master
  provider: script
  script:
  - npm run build
  - npx semantic-release
